input {
    tcp {
        port => 5000
        codec => json
        host => "0.0.0.0" # This is crucial
    }
}
output {
    elasticsearch {
        # Logstash service name and port within the docker-compose network
        hosts => ["http://elasticsearch:9200"]
        # Index name where logs will be stored (use a date pattern for daily indices)
        index => "spring-boot-logs-%{+YYYY.MM.dd}"
    }
    stdout {
        codec => rubydebug # Optional: for debugging Logstash output
    }
}