CREATE TABLE se.user_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    email         VARCHAR(255),
    date_of_birth date,
    CONSTRAINT pk_user_entity PRIMARY KEY (id)
);